import os
from pathlib import Path

from dotenv import load_dotenv
from pydantic import BaseModel, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


BACKEND_DIR = Path(__file__).resolve().parent
load_dotenv(BACKEND_DIR / ".env", override=True)
FEATURE_FLAG_DEFAULTS = {
    "ARCHITECTURE_GOVERNOR_ENABLED": True,
    "PIPELINE_ORCHESTRATOR_ENABLED": True,
    "WORKFLOW_ENGINE_ENABLED": True,
    "TASK_PLANNER_ENABLED": True,
    "ADAPTIVE_PLANNER_ENABLED": True,
    "EXECUTION_POLICY_ENABLED": True,
    "RUNTIME_METRICS_ENABLED": True,
    "EVIDENCE_ENGINE_ENABLED": True,
    "EVIDENCE_REASONER_ENABLED": True,
    "EVIDENCE_VERIFICATION_ENABLED": True,
    "ANSWER_CONTEXT_ENABLED": True,
    "STRUCTURED_REASONING_ENABLED": True,
    "SELF_REFLECTION_ENABLED": True,
    "AUTO_REPAIR_PLANNER_ENABLED": True,
    "AUTO_REPAIR_EXECUTION_ENABLED": True,
    "REGRESSION_FRAMEWORK_ENABLED": True,
    "E2E_EVALUATION_ENABLED": True,
    # Compatibility flags already used in the current runtime.
    "ANSWER_COMPOSER_ENABLED": True,
    "RETRIEVAL_LOOP_ENABLED": True,
    "KNOWLEDGE_LAYER_ENABLED": True,
    "MEMORY_LAYER_ENABLED": True,
    "TRACE_CENTER_ENABLED": True,
    "SERVICE_CONTAINER_ENABLED": True,
    "TOOL_REGISTRY_ENABLED": True,
    "CAPABILITY_PLANNER_ENABLED": True,
    "REASONING_ENGINE_V1_ENABLED": True,
    "BENCHMARK_FRAMEWORK_ENABLED": True,
    "INSIGHT_ENGINE_ENABLED": False,
    "INSIGHT_FINAL_RENDER_ENABLED": False,
    "WATCH_ALERT_V1_ENABLED": False,
    "WATCH_ALERT_SCHEDULER_ENABLED": False,
    "WATCH_ALERT_NOTIFICATIONS_ENABLED": False,
    "AUTH_V1_ENABLED": False,
    "AUTH_COOKIE_REQUIRED": False,
}


class FeatureFlags(BaseModel):
    ARCHITECTURE_GOVERNOR_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ARCHITECTURE_GOVERNOR_ENABLED"]
    PIPELINE_ORCHESTRATOR_ENABLED: bool = FEATURE_FLAG_DEFAULTS["PIPELINE_ORCHESTRATOR_ENABLED"]
    WORKFLOW_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WORKFLOW_ENGINE_ENABLED"]
    TASK_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TASK_PLANNER_ENABLED"]
    ADAPTIVE_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ADAPTIVE_PLANNER_ENABLED"]
    EXECUTION_POLICY_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EXECUTION_POLICY_ENABLED"]
    RUNTIME_METRICS_ENABLED: bool = FEATURE_FLAG_DEFAULTS["RUNTIME_METRICS_ENABLED"]
    EVIDENCE_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_ENGINE_ENABLED"]
    EVIDENCE_REASONER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_REASONER_ENABLED"]
    EVIDENCE_VERIFICATION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_VERIFICATION_ENABLED"]
    ANSWER_CONTEXT_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ANSWER_CONTEXT_ENABLED"]
    STRUCTURED_REASONING_ENABLED: bool = FEATURE_FLAG_DEFAULTS["STRUCTURED_REASONING_ENABLED"]
    SELF_REFLECTION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["SELF_REFLECTION_ENABLED"]
    AUTO_REPAIR_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTO_REPAIR_PLANNER_ENABLED"]
    AUTO_REPAIR_EXECUTION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTO_REPAIR_EXECUTION_ENABLED"]
    REGRESSION_FRAMEWORK_ENABLED: bool = FEATURE_FLAG_DEFAULTS["REGRESSION_FRAMEWORK_ENABLED"]
    E2E_EVALUATION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["E2E_EVALUATION_ENABLED"]
    ANSWER_COMPOSER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ANSWER_COMPOSER_ENABLED"]
    RETRIEVAL_LOOP_ENABLED: bool = FEATURE_FLAG_DEFAULTS["RETRIEVAL_LOOP_ENABLED"]
    KNOWLEDGE_LAYER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["KNOWLEDGE_LAYER_ENABLED"]
    MEMORY_LAYER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["MEMORY_LAYER_ENABLED"]
    TRACE_CENTER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TRACE_CENTER_ENABLED"]
    SERVICE_CONTAINER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["SERVICE_CONTAINER_ENABLED"]
    TOOL_REGISTRY_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TOOL_REGISTRY_ENABLED"]
    CAPABILITY_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["CAPABILITY_PLANNER_ENABLED"]
    REASONING_ENGINE_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["REASONING_ENGINE_V1_ENABLED"]
    BENCHMARK_FRAMEWORK_ENABLED: bool = FEATURE_FLAG_DEFAULTS["BENCHMARK_FRAMEWORK_ENABLED"]
    INSIGHT_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["INSIGHT_ENGINE_ENABLED"]
    INSIGHT_FINAL_RENDER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["INSIGHT_FINAL_RENDER_ENABLED"]
    WATCH_ALERT_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_V1_ENABLED"]
    WATCH_ALERT_SCHEDULER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_SCHEDULER_ENABLED"]
    WATCH_ALERT_NOTIFICATIONS_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_NOTIFICATIONS_ENABLED"]
    AUTH_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTH_V1_ENABLED"]
    AUTH_COOKIE_REQUIRED: bool = FEATURE_FLAG_DEFAULTS["AUTH_COOKIE_REQUIRED"]

    def to_dict(self) -> dict[str, bool]:
        return {name: bool(value) for name, value in self.model_dump().items()}

    def to_env(self) -> dict[str, str]:
        return {name: "true" if value else "false" for name, value in self.to_dict().items()}


class ProviderConfig(BaseModel):
    provider: str = "deepseek"
    api_key: str = ""
    base_url: str = "https://api.deepseek.com/v1"
    model: str = "deepseek-chat"


class Settings(BaseSettings):
    DATABASE_URL: str = f"sqlite:///{(BACKEND_DIR / 'cio_intelligence.db').as_posix()}"
    LLM_PROVIDER: str = "deepseek"
    DEEPSEEK_API_KEY: str = ""
    DEEPSEEK_BASE_URL: str = "https://api.deepseek.com/v1"
    DEEPSEEK_MODEL: str = "deepseek-chat"
    ARCHITECTURE_GOVERNOR_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ARCHITECTURE_GOVERNOR_ENABLED"]
    PIPELINE_ORCHESTRATOR_ENABLED: bool = FEATURE_FLAG_DEFAULTS["PIPELINE_ORCHESTRATOR_ENABLED"]
    WORKFLOW_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WORKFLOW_ENGINE_ENABLED"]
    TASK_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TASK_PLANNER_ENABLED"]
    ADAPTIVE_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ADAPTIVE_PLANNER_ENABLED"]
    EXECUTION_POLICY_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EXECUTION_POLICY_ENABLED"]
    RUNTIME_METRICS_ENABLED: bool = FEATURE_FLAG_DEFAULTS["RUNTIME_METRICS_ENABLED"]
    EVIDENCE_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_ENGINE_ENABLED"]
    EVIDENCE_REASONER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_REASONER_ENABLED"]
    EVIDENCE_VERIFICATION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["EVIDENCE_VERIFICATION_ENABLED"]
    ANSWER_CONTEXT_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ANSWER_CONTEXT_ENABLED"]
    STRUCTURED_REASONING_ENABLED: bool = FEATURE_FLAG_DEFAULTS["STRUCTURED_REASONING_ENABLED"]
    SELF_REFLECTION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["SELF_REFLECTION_ENABLED"]
    AUTO_REPAIR_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTO_REPAIR_PLANNER_ENABLED"]
    AUTO_REPAIR_EXECUTION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTO_REPAIR_EXECUTION_ENABLED"]
    REGRESSION_FRAMEWORK_ENABLED: bool = FEATURE_FLAG_DEFAULTS["REGRESSION_FRAMEWORK_ENABLED"]
    E2E_EVALUATION_ENABLED: bool = FEATURE_FLAG_DEFAULTS["E2E_EVALUATION_ENABLED"]
    ANSWER_COMPOSER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["ANSWER_COMPOSER_ENABLED"]
    RETRIEVAL_LOOP_ENABLED: bool = FEATURE_FLAG_DEFAULTS["RETRIEVAL_LOOP_ENABLED"]
    KNOWLEDGE_LAYER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["KNOWLEDGE_LAYER_ENABLED"]
    MEMORY_LAYER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["MEMORY_LAYER_ENABLED"]
    TRACE_CENTER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TRACE_CENTER_ENABLED"]
    SERVICE_CONTAINER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["SERVICE_CONTAINER_ENABLED"]
    TOOL_REGISTRY_ENABLED: bool = FEATURE_FLAG_DEFAULTS["TOOL_REGISTRY_ENABLED"]
    CAPABILITY_PLANNER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["CAPABILITY_PLANNER_ENABLED"]
    REASONING_ENGINE_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["REASONING_ENGINE_V1_ENABLED"]
    BENCHMARK_FRAMEWORK_ENABLED: bool = FEATURE_FLAG_DEFAULTS["BENCHMARK_FRAMEWORK_ENABLED"]
    INSIGHT_ENGINE_ENABLED: bool = FEATURE_FLAG_DEFAULTS["INSIGHT_ENGINE_ENABLED"]
    INSIGHT_FINAL_RENDER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["INSIGHT_FINAL_RENDER_ENABLED"]
    WATCH_ALERT_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_V1_ENABLED"]
    WATCH_ALERT_SCHEDULER_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_SCHEDULER_ENABLED"]
    WATCH_ALERT_NOTIFICATIONS_ENABLED: bool = FEATURE_FLAG_DEFAULTS["WATCH_ALERT_NOTIFICATIONS_ENABLED"]
    AUTH_V1_ENABLED: bool = FEATURE_FLAG_DEFAULTS["AUTH_V1_ENABLED"]
    AUTH_COOKIE_REQUIRED: bool = FEATURE_FLAG_DEFAULTS["AUTH_COOKIE_REQUIRED"]
    WATCH_ALERT_SCHEDULER_INTERVAL_SECONDS: int = 300
    WATCH_ALERT_MAX_RETRIES: int = 3
    WATCH_ALERT_RETRY_BASE_SECONDS: int = 300
    WATCH_ALERT_MAX_CONSECUTIVE_FAILURES: int = 5
    model_config = SettingsConfigDict(env_file=str(BACKEND_DIR / ".env"), extra="ignore")

    @model_validator(mode="after")
    def normalize_database_url(self):
        if self.DATABASE_URL.startswith("sqlite:///"):
            raw_path = self.DATABASE_URL[len("sqlite:///") :]
            db_path = Path(raw_path)
            if not db_path.is_absolute():
                self.DATABASE_URL = f"sqlite:///{(BACKEND_DIR / db_path).resolve().as_posix()}"
        return self

    @property
    def FEATURE_FLAGS(self) -> FeatureFlags:
        return FeatureFlags(
            **{name: bool(getattr(self, name)) for name in FEATURE_FLAG_DEFAULTS}
        )

    @property
    def PROVIDER_CONFIG(self) -> ProviderConfig:
        deepseek_key = str(self.DEEPSEEK_API_KEY or "").strip()
        provider = str(self.LLM_PROVIDER or "").strip().lower()
        if deepseek_key:
            return ProviderConfig(
                provider="deepseek",
                api_key=deepseek_key,
                base_url=str(self.DEEPSEEK_BASE_URL or "https://api.deepseek.com/v1").rstrip("/"),
                model=str(self.DEEPSEEK_MODEL or "deepseek-chat").strip(),
            )
        return ProviderConfig(provider=(provider or "deepseek"))

    def feature_flag(self, name: str, default: bool | None = None) -> bool:
        normalized_name = str(name or "").strip().upper()
        if normalized_name in FEATURE_FLAG_DEFAULTS:
            return bool(getattr(self, normalized_name))
        if default is not None:
            return bool(default)
        return False

settings = Settings()


def sync_feature_flags_to_env(*, override: bool = True) -> dict[str, str]:
    env_map = settings.FEATURE_FLAGS.to_env()
    for name, value in env_map.items():
        if override or name not in os.environ:
            os.environ[name] = value
    return env_map
